spring:
  datasource:
    url: jdbc:postgresql://budget-db:5432/budgetdb
    username: budget
    password: budgetpass

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true

server:
  port: 8082

jwt:
  secret: change-this-secret-to-a-strong-random-value
  expiration-ms: 86400000 # 1 day
